import greatPyramid from '../assets/Great Pyramid of Giza.jpg';
import qaitbay from '../assets/Citadel of Qaitbay.jpg';
import karnak from '../assets/Karnak Temple Complex.jpg';
import philae from '../assets/Philae Temple.jpg';
import rasMohammed from '../assets/Ras Mohammed National Park.jpg';
import blueHole from '../assets/Blue Hole.jpg';
import cleopatra from '../assets/Cleopatra\'s Bath.jpg'; // Escaped apostrophe
import giftun from '../assets/Giftun Island.jpg';
import abuSimbel from '../assets/Abu Simbel Temples.jpg';
import elGouna from '../assets/El Gouna Lagoons.jpg';
import whiteDesert from '../assets/White Desert National Park.jpg';
import marsaNayzak from '../assets/Marsa Nayzak.jpg';
import mountSinai from '../assets/Mount Sinai Hike.jpg';
import wadiElHitan from '../assets/Wadi El Hitan.jpg';
import baronPalace from '../assets/Baron Empain Palace.jpg';
import valleyKings from '../assets/Valley of the Kings.jpg';
import salahCitadel from '../assets/Salah El-Din Citadel.jpg';
import bibliotheca from '../assets/Bibliotheca Alexandrina.jpg';
import khanKhalili from '../assets/Khan el-Khalili.jpg';
import ageeba from '../assets/Ageeba Beach.jpg';
import coloredCanyon from '../assets/Colored Canyon.jpg';
import wadiDegla from '../assets/Wadi Degla Protectorate.jpg';

export const DESTINATIONS_DATA = [
  {
    id: 1,
    name: "Great Pyramid of Giza",
    governorate: "Cairo",
    location: "Al Haram, Giza Plateau",
    type: "Historical",
    budget: "Medium",
    budgetLevel: 2,
    ticketFee: "540 EGP",
    image: greatPyramid,
    description: "The oldest of the Seven Wonders of the Ancient World. Experience the grandeur of Khufu's pyramid and the Sphinx.",
  },
  {
    id: 2,
    name: "Citadel of Qaitbay",
    governorate: "Alexandria",
    location: "Eastern Harbor, Alexandria",
    type: "Historical",
    budget: "Low",
    budgetLevel: 1,
    ticketFee: "100 EGP",
    image: qaitbay,
    description: "A 15th-century defensive fortress located on the Mediterranean coast, built upon the ruins of the Lighthouse of Alexandria.",
  },
  {
    id: 3,
    name: "Karnak Temple Complex",
    governorate: "Luxor",
    location: "Karnak, Luxor",
    type: "Historical",
    budget: "Medium",
    budgetLevel: 2,
    ticketFee: "450 EGP",
    image: karnak,
    description: "The largest religious building ever constructed. Walk through the Hypostyle Hall with its 134 massive sandstone columns.",
  },
  {
    id: 4,
    name: "Philae Temple",
    governorate: "Aswan",
    location: "Agilkia Island, Aswan",
    type: "Historical",
    budget: "Medium",
    budgetLevel: 2,
    ticketFee: "450 EGP",
    image: philae,
    description: "Dedicated to the goddess Isis, this temple was dismantled and relocated to Agilkia Island to save it from flooding.",
  },
  {
    id: 9,
    name: "Abu Simbel Temples",
    governorate: "Aswan",
    location: "Abu Simbel",
    type: "Historical",
    budget: "High",
    budgetLevel: 3,
    ticketFee: "615 EGP (+ Transport)",
    image: abuSimbel,
    description: "Two massive rock temples at Abu Simbel, a village in Nubia, southern Egypt, near the border with Sudan.",
  },
  {
    id: 15,
    name: "Baron Empain Palace",
    governorate: "Cairo",
    location: "Heliopolis",
    type: "Historical",
    budget: "Low",
    budgetLevel: 1,
    ticketFee: "60 EGP",
    image: baronPalace,
    description: "A distinctive and historic Hindu temple-inspired mansion in Heliopolis, recently restored to its former glory.",
  },
  {
    id: 16,
    name: "Valley of the Kings",
    governorate: "Luxor",
    location: "West Bank, Luxor",
    type: "Historical",
    budget: "High",
    budgetLevel: 3,
    ticketFee: "600 EGP",
    image: valleyKings,
    description: "The burial site of almost all the pharaohs of the 18th, 19th, and 20th dynasties, including Tutankhamun and Ramesses II.",
  },
  {
    id: 17,
    name: "Salah El-Din Citadel",
    governorate: "Cairo",
    location: "Mokattam Hills",
    type: "Historical",
    budget: "Medium",
    budgetLevel: 2,
    ticketFee: "450 EGP",
    image: salahCitadel,
    description: "A medieval Islamic-era fortification in Cairo, famous for its panoramic views of the city and the stunning Mosque of Muhammad Ali.",
  },
  {
    id: 18,
    name: "Bibliotheca Alexandrina",
    governorate: "Alexandria",
    location: "Shatby, Alexandria",
    type: "Historical",
    budget: "Low",
    budgetLevel: 1,
    ticketFee: "100 EGP",
    image: bibliotheca,
    description: "A major library and cultural center commemorating the Library of Alexandria that was lost in antiquity.",
  },
  {
    id: 19,
    name: "Khan el-Khalili",
    governorate: "Cairo",
    location: "Islamic Cairo",
    type: "Historical",
    budget: "Low",
    budgetLevel: 1,
    ticketFee: "Free Entry",
    image: khanKhalili,
    description: "A famous bazaar and souq in the historic center of Cairo. Perfect for shopping for spices, jewelry, and souvenirs.",
  },
  {
    id: 5,
    name: "Ras Mohammed National Park",
    governorate: "South Sinai",
    location: "Sharm El Sheikh",
    type: "Coastal",
    budget: "Low",
    budgetLevel: 1,
    ticketFee: "250 EGP",
    image: rasMohammed,
    description: "Egypt's most famous national park, offering some of the world's best diving and snorkeling spots with vibrant coral reefs.",
  },
  {
    id: 6,
    name: "Blue Hole",
    governorate: "South Sinai",
    location: "Dahab",
    type: "Coastal",
    budget: "Low",
    budgetLevel: 1,
    ticketFee: "300 EGP",
    image: blueHole,
    description: "A submarine sinkhole and legendary dive site. A paradise for freedivers and technical divers from around the globe.",
  },
  {
    id: 8,
    name: "Giftun Island",
    governorate: "Red Sea",
    location: "Hurghada",
    type: "Coastal",
    budget: "High",
    budgetLevel: 3,
    ticketFee: "Varies",
    image: giftun,
    description: "A pristine island protectorate with sandy beaches and turquoise waters, perfect for a day trip of snorkeling and sunbathing.",
  },
  {
    id: 10,
    name: "El Gouna Lagoons",
    governorate: "Red Sea",
    location: "El Gouna",
    type: "Coastal",
    budget: "High",
    budgetLevel: 3,
    ticketFee: "Free Access",
    image: elGouna,
    description: "A modern resort town built on islands and lagoons. Known for kitesurfing, luxury yachts, and vibrant nightlife.",
  },
  {
    id: 12,
    name: "Marsa Nayzak",
    governorate: "Red Sea",
    location: "Marsa Alam",
    type: "Coastal",
    budget: "Medium",
    budgetLevel: 2,
    ticketFee: "Free",
    image: marsaNayzak,
    description: "A natural pool formed by a meteor strike, offering warm waters and a unique swimming experience south of Marsa Alam.",
  },
  {
    id: 20,
    name: "Ageeba Beach",
    governorate: "Matrouh",
    location: "Marsa Matrouh",
    type: "Coastal",
    budget: "Low",
    budgetLevel: 1,
    ticketFee: "20 EGP",
    image: ageeba,
    description: "Known for its stunning turquoise waters and dramatic cliff formations. 'Ageeba' means 'Wonder' in Arabic.",
  },
  {
    id: 7,
    name: "Cleopatra's Bath",
    governorate: "Matrouh",
    location: "Siwa Oasis",
    type: "Nature",
    budget: "Low",
    budgetLevel: 1,
    ticketFee: "Free",
    image: cleopatra,
    description: "A historic natural spring where you can swim in crystal clear waters surrounded by palm groves in the heart of the oasis.",
  },
  {
    id: 11,
    name: "White Desert National Park",
    governorate: "New Valley",
    location: "Farafra Depression",
    type: "Nature",
    budget: "Medium",
    budgetLevel: 2,
    ticketFee: "5 USD",
    image: whiteDesert,
    description: "Famous for its dramatic white chalk rock formations created by sandstorms. A surreal landscape perfect for camping.",
  },
  {
    id: 13,
    name: "Mount Sinai Hike",
    governorate: "South Sinai",
    location: "Saint Catherine",
    type: "Nature",
    budget: "Medium",
    budgetLevel: 2,
    ticketFee: "Guide Required",
    image: mountSinai,
    description: "A spiritual and physical journey. Hike up to the summit for a breathtaking sunrise over the rugged Sinai mountains.",
  },
  {
    id: 14,
    name: "Wadi El Hitan (Whale Valley)",
    governorate: "Fayoum",
    location: "Fayoum Oasis",
    type: "Nature",
    budget: "High",
    budgetLevel: 3,
    ticketFee: "400 EGP (Safari)",
    image: wadiElHitan,
    description: "A UNESCO World Heritage site containing invaluable fossil remains of the earliest, and now extinct, suborder of whales.",
  },
  {
    id: 21,
    name: "Colored Canyon",
    governorate: "South Sinai",
    location: "Nuweiba",
    type: "Nature",
    budget: "Medium",
    budgetLevel: 2,
    ticketFee: "Guide Required",
    image: coloredCanyon,
    description: "A rock formation on the Sinai peninsula. It is a labyrinth of rocks, some up to 40 meters high, colored in shades of yellow, purple, and red.",
  },
  {
    id: 22,
    name: "Wadi Degla Protectorate",
    governorate: "Cairo",
    location: "Maadi",
    type: "Nature",
    budget: "Low",
    budgetLevel: 1,
    ticketFee: "5 USD",
    image: wadiDegla,
    description: "A slice of desert nature right on the edge of Cairo. Perfect for hiking, running, and escaping the city noise.",
  },
];